In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
df = pd.read_csv(r'/home/mukul/Main/Basic_DataScience-4ML/assets/data/anime.csv')

In [43]:
df

,Rank,Title,Score
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71

In [ ]:
df.info()

Extract number of ep

In [ ]:
# def extract(txt):
#     ans = ""
#     flag = False
#     for i in txt:
#         if i=="(":
#             flag = True
#             continue
#         if i == ")":
#             flag = False
#         if flag:
#             ans += i
#     return ans
# df["Episodes"] = df["Title"].apply(extract)
# df["Episodes"] = df["Episodes"].str.replace("eps","")
# df["Episodes"] = df["Episodes"].astype(int)

df["Episodes"] = df["Title"].str.extract(r'/((\d)/')

In [ ]:
df

In [ ]:
# def timestamp(txt):
#     ans = ""
#     i = 0
#     while i < len(txt):
#         if txt[i] == ")":
#             # Extract next 20 chars SAFELY after ")"
#             for j in range(i+1, min(i+21, len(txt))):
#                 ans += txt[j]
#             return ans
#         i += 1
#     return ans
#
#
# df["Timestamp"] = df["Title"].apply(timestamp)

In [ ]:
df

In [ ]:
# Extract text 20 chars after FIRST ")"
df["Timestamp"] = df["Title"].str.extract(r'\)(.{0,20})')[0]

In [38]:
df

,Rank,Title,Score,Timestamp
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,1
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,1
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,7
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,74
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,1
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,1
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,12
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,1
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,24
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,23
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,12
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,26
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,13
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,16
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,11
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,11
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,10
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,1
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,26
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,12
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,26
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,24
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,10
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,12
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,12
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,4

In [ ]:
df.info()

In [ ]:
pd.set_option('display.max_colwidth', None)
print(df["Title"])

In [39]:
df["Timestamp"] = df["Title"].str.extract(r'\((\d+)')

In [40]:
df

,Rank,Title,Score,Timestamp
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,1
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,1
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,7
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,74
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,1
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,1
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,12
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,1
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,24
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,23
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,12
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,26
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,13
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,16
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,11
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,11
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,10
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,1
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,26
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,12
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,26
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,24
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,10
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,12
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,12
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,4